name: Release Artifacts

on:
  workflow_run:
    workflows:
      - "CMake (Linux)"
      - "CMake (macos)"
      - "CMake (Windows, msys2)"
    types:
      - completed

jobs:
  upload-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency:
      group: release-artifacts-${{ github.event.workflow_run.head_sha }}
      cancel-in-progress: true
    steps:
      - name: Wait for all builds to finish
        uses: WyriHaximus/github-action-wait-for-status@v2
        with:
          ignoreActions: "Release Artifacts"
          checkInterval: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts from builds
        run: |
          mkdir -p artifacts
          workflows=(cmake_linux.yml cmake_macos.yml cmake_windows_msys2.yml)
          for wf in "${workflows[@]}"; do
            id=$(gh api \
              /repos/${GITHUB_REPOSITORY}/actions/workflows/$wf/runs \
              -f head_sha=${{ github.event.workflow_run.head_sha }} \
              -f status=completed \
              -q '.workflow_runs[0].id')
            if [ -z "$id" ]; then
              echo "No run found for $wf" >&2
              exit 1
            fi
            gh run download "$id" -D artifacts
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare release archives
        run: |
          mkdir -p release
          cwd=$(pwd)
          for d in artifacts/*; do
            [ -d "$d" ] || continue
            name=$(basename "$d")
            if [ -d "$d/build/artifacts" ]; then
              content="$d/build/artifacts"
            else
              content="$d"
            fi

            if [ ! -e "$content" ]; then
              echo "No content found in $d" >&2
              continue
            fi

            tmpdir=$(mktemp -d)
            cp -r "$content"/* "$tmpdir/"
            (cd "$tmpdir" && zip -r "$cwd/release/${name}.zip" .)
            rm -rf "$tmpdir"
          done

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: gha-${{ github.event.workflow_run.head_sha }}
          name: Automated build for ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          files: release/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite_files: true
          append_body: true
